# Generated by Django 4.2.6 on 2023-10-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurantrequest_corresponding_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantrequest',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
