# Generated by Django 4.2.6 on 2023-11-08 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_restaurantrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
