# Generated by Django 4.2.6 on 2023-11-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_restaurantrequest_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menurequest',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantrequest',
            name='menu_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuRequest',
        ),
    ]
