# Generated by Django 4.2.6 on 2023-11-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_report_remove_crowdednessreport_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectionmessage',
            name='for_what',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('CL', 'Cleanliness'), ('CR', 'Crowdedness'), ('FR', 'Friendliness'), ('MQ', 'Menu Quality')], default='CL', max_length=2),
        ),
    ]
