# Generated by Django 4.2.6 on 2023-12-01 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rejectionmessage_for_what_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0, message='Latitude must be at least -90'), django.core.validators.MaxValueValidator(90.0, message='Latitude must be at most 90')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0, message='Longitude must be at least -90'), django.core.validators.MaxValueValidator(180.0, message='Longitude must be at most 90')]),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='latitude',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-90.0, message='Latitude must be at least -90'), django.core.validators.MaxValueValidator(90.0, message='Latitude must be at most 90')]),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='longitude',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-180.0, message='Longitude must be at least -90'), django.core.validators.MaxValueValidator(180.0, message='Longitude must be at most 90')]),
        ),
    ]
